### ISSUE TITLE
Shader error in 'GPUPhysicsComputeShader.compute': Macro names must be identifiers at kernel ClearGrid at <predefined macros>(12) (on metal)

### ISSUE THREAD

**Issue by rndD** [jknightdoeswork/gpu-physics-unity#1]
Hello. I have this error after importing your code in unity 2018.

Anyway, cool results with voxels! Thanks for the code, maybe I will figure it out how to fix it.

**Comment by jknightdoeswork** [comment]
Yeah this shows up on Vulkan. It works if you force openGL.

Posting a minified example containing this error to the Unity forum should
get an answer.

On Jan 19, 2019 2:01 PM, "Alex Kalmakov" <notifications@github.com> wrote:

Hello. I have this error after importing your code in unity 2018.

Anyway, cool results with voxels! Thanks for the code, maybe I will figure
it out how to fix it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jknightdoeswork/gpu-physics-unity/issues/1>, or mute
the thread

**Comment by jknightdoeswork** [comment]
Oh wait you say it happens on Metal as well now... Crap! Thanks for the
heads up.

**Comment by rndD** [comment]
yeap! it happens on Metal

**Comment by alerdenisov** [comment]
It's can be easy fixed. We shouldn't put any comments in macro defines: 

```
// Kernels
// Per Rigid Body	0
#pragma kernel GenerateParticleValues

// Per Grid Cell	1
#pragma kernel ClearGrid

// Per Particle		2
#pragma kernel PopulateGrid

// Per Particle		3
#pragma kernel CollisionDetection

// Per Rigid Body	4
#pragma kernel ComputeMomenta

// Per Rigid Body	5
#pragma kernel ComputePositionAndRotation

// Per Rigid Body	6
#pragma kernel SavePreviousPositionAndRotation
```

**Comment by jknightdoeswork** [comment]
Fixed by @alerdenisov . Thank you so much
https://github.com/jknightdoeswork/gpu-physics-unity/pull/2
